version: '3'
services:
  x3ngine-api:
    build: .
    volumes:
      - .:/usr/src/app  # Mount local source code to the container (for development)
      - '/usr/src/app/node_modules'
    environment:
      NODE_ENV: production
    networks:
      - x3ngine-network
  nginx-x3ngine-api:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx config
    ports:
      - "8000:8000"  # Expose port 80 for the Nginx reverse proxy
    depends_on:
      - x3ngine-api  # Ensure Nginx starts after the Node.js app
    networks:
      - x3ngine-network
networks:
  x3ngine-network:
    driver: bridge